app:
  version: pro
message: Spring Cloud Config Demo
spring:
  rabbitmq:
    host: localhost
spring:
  rabbitmq:
    port: 5673
spring:
  rabbitmq:
    username: guest
spring:
  rabbitmq:
    password: guest
spring:
  xxx:
    password: {cipher}1
server:
  port: 8008
