app:
  version: prod
message: Spring Cloud Config Demo Prod 222222
spring:
  encrypt:
    password: "{cipher}AQAtKEUzI052CUAEJk8R3BxOiNBEKXeeoyZIPW71DcdzgXaUf25ulK8iMsFKLH4HPu0rufTB9u+eclW5FgPKlp2b06yNi/X9n+Hc5/SQX5H+/FrVz+J2ppbuUy/V8Z7is0/4BB1g0BtU6wF/I085GPdWK0wA74nmKMWRj7QwOodgmkt3B4UBWWKVa+dWJxFIbOT/JWZ1mLs6vw67IKZ83+5cuQl8m6pKt1yblgh1/8kXVfzP0sf1xjJdpYM+AxIXZRkcQdED7N26A2HC5MrKtgrMABG+6vsV4rhdqEjKUCxFXe0By60NDH8YqFHQ6tZi1OPKs/JUD0Xq7rjwxlkQWizxFwo4/Ts8LZGY3fAX56fWwWMnaK4aZgcBrRvESMAJQ1g="
server:
  port: 8008
